# -*- coding: utf-8 -*-
"""Stable diffussion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g76z9l6VRrHY_laMA1E0RfF7FmCDD65z
"""

!pip install --upgrade diffusers transformers -q

!pip install pycuda

import torch
from diffusers import StableDiffusionXLPipeline, DPMSolverMultistepScheduler
from PIL import Image

class CFG:
    # check if GPU is available, otherwise use CPU (though CPU is very slow)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    seed = 42
    # Switched to 2-1-base which works better at 512x512 resolution
    image_gen_model_id = "stabilityai/stable-diffusion-xl-base-1.0" # Changed to a publicly available SDXL model
    image_gen_steps = 30  # 30 steps is usually enough with DPM Solver
    image_gen_size = (512, 512)
    image_gen_guidance_scale = 7.5 # Standard scale for good adherence to prompt

print(f"Loading model on {CFG.device}...")

# Load the model
# Note: We use torch.float16 for GPU to save memory. If using CPU, remove torch_dtype.
pipe = StableDiffusionXLPipeline.from_pretrained(
    CFG.image_gen_model_id,
    torch_dtype=torch.float16 if CFG.device == "cuda" else torch.float32
)

# Use DPM Solver Scheduler (Faster and better quality)
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
pipe = pipe.to(CFG.device)

# Optional: Enable memory optimizations if you have low VRAM (<8GB)
# pipe.enable_attention_slicing()

def generate_image(prompt, filename_to_save):
    print(f"Generating: '{prompt}'")

    # Create the generator for reproducibility
    generator = torch.Generator(CFG.device).manual_seed(CFG.seed)

    image = pipe(
        prompt,
        height=CFG.image_gen_size[0],
        width=CFG.image_gen_size[1],
        num_inference_steps=CFG.image_gen_steps,
        guidance_scale=CFG.image_gen_guidance_scale,
        generator=generator
    ).images[0]

    # THIS IS THE FIX: Save the image to your computer
    image.save(filename_to_save)
    print(f"Success! Image saved as {filename_to_save}")
    return image

# Run the generation
generate_image(
    "a man in the swiming pool",
    "mars_astronaut.png"
)